name: Hardcore
author: DaytonJWatson
description: 'custom hardcore plugin'
version: 0.0.1
api-version: '1.21'
main: com.daytonjwatson.hardcore.HardcorePlugin
commands:
  guide:
    description: Opens the Bandits & Heroes guide.
  discord:
    description: Shares the Hardcore Discord invite.
  help:
    description: Lists available Hardcore commands.
  rules:
    description: Shows Hardcore server rules.
  stats:
    description: Shows player stats.
    usage: /stats [player]
  admin:
    description: Hardcore admin tooling.
    usage: /admin <action>
    aliases: [a]
  bandittracker:
    description: Recalibrates your crafted bandit tracker and shows its recipe.
    aliases: [trackbandit, huntbandit]
    usage: /bandittracker [recipe]
  bank:
    description: Opens your Hardcore bank account.
    usage: /bank [balance|transactions|send]
  pay:
    description: Quick shortcut for sending money to another player.
    usage: /pay <player> <amount>
  auction:
    description: Opens the Hardcore auction house.
    usage: /auction [page|add]
    aliases: [ah]